### ISSUE TITLE
[FEATURE] Add a theme switcher button like dark and light theme 

### ISSUE THREAD

**Issue by vaibhavsharma1234** [Susmita-Dey/Sukoon#64]
i am a ssoc participant

**Comment by vaibhavsharma1234** [comment]
which level of issue is this ?

**Comment by vaibhavsharma1234** [comment]
Currently working on this just a little busy due to college

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by Susmita-Dey** [comment]
@vaibhavsharma1234 First complete your previous issues.

**Comment by Susmita-Dey** [comment]
> pls assign me this issue

go ahead

**Comment by vaibhavsharma1234** [comment]
i only have one issue left 
i could have done this too

**Comment by Susmita-Dey** [comment]
> i only have one issue left i could have done this too

Complete that first

**Comment by AnshuPathak-88825** [comment]
Hey @Susmita-Dey  I 've created theme changer but now I'm facing problem  should I remove background image and add gradient colour to it because if we change colour then background image won't change that's why I'm asking pls let me know what should I do ?
[Screencast from 09-08-22 07:57:43 PM IST.webm](https://user-images.githubusercontent.com/78332454/183675489-68d4a4f4-5cf5-4544-8aae-50f1a0212ebd.webm)

**Comment by Susmita-Dey** [comment]
@vaibhavsharma1234 Do you want to make a theme changes as in the video?
If yes, then it would remove the navbar and the hero section which is a drastic change and also not allowed.
